### ISSUE TITLE
database is not updated via the API

### ISSUE THREAD

**Issue by GelmutShmidt** [aarreedd/bitcoinabuse.com#14]
When downloading the database , the database is not updated beyond 2020-12-15T03:15:49.000000 Z.

**Comment by aarreedd** [comment]
From the API Docs: 

> The "1d" file is updated daily in the early morning. The "30d" file is updated weekly on Sunday morning. The "forever" file is updated monthly on the 15th of the month. All updates occur between 2am-3am UTC.

https://www.bitcoinabuse.com/api-docs#download
