### ISSUE TITLE
https://www.bitcoinabuse.com/api/abuse-types requires 'login'

### ISSUE THREAD

**Issue by hb9eue** [aarreedd/bitcoinabuse.com#8]
Hi

Nice project, over which I stumbled checking if there is a DNS based BTC Address blacklist useable with SpamAssassin or similar.

I operate part of the SWINOG Spamtraps / Honeypot which pretend to be open mail relay and accept authentication with any SMTP username / password. Lately I started seeing a lot of attempt to relay sextortion emails via my trap.

So why not match the BTC Address in those emails with some simple regex and feed to your service?

So let's start coding. Registered. Got API Key. Doh! I could not figure out how to get the list of abuse_types integers. I suppose that should not redirect to the login page...

-Benoit-

**Comment by aarreedd** [comment]
The API requires an API key. Create a free account and generate an API.
Then specify the API key with the query string parameter `api_token`.

**Comment by hb9eue** [comment]
According to the documentation [1], the api_token is not required for the function: 'abuse-types'.
Please update docs :-)

[1]https://www.bitcoinabuse.com/api-docs#abuse_types

**Comment by MikeBocko** [comment]
An api_token is no longer required to view abuse-types.
